"""The adjudication core — the only thing that may decide how a ruling turns out.

Holds the read surface, the legality derivation, adjudication, the trigger matcher,
the ledger, and the memory-port protocol. Two import rules bound this package, and
`tests/test_layer_boundaries.py` enforces both:

1. Nothing here may import from an outer layer. An empty `[project].dependencies`
   constrains what the package pulls in from outside, not how its own layers depend
   on each other — a core module importing an adapter would break R33 while that
   list still read empty.
2. Nothing outside the core may import a *submodule* of this package. Outer layers
   use what this module re-exports, which is what makes R34's "built over the same
   contract" a fact about the import graph rather than a description of intent.

See `docs/decisions/0011-module-layout-and-versioning.md`.
"""

from __future__ import annotations

from srd_rules_engine.core.adjudicate import (
    Adjudicator,
    DamageDice,
    Declaration,
    Effect,
    EffectKind,
    Intent,
    NarrationBounds,
    Proposal,
    RejectionCode,
    Resolver,
    Ruling,
    Status,
)
from srd_rules_engine.core.canonical import (
    MAX_SAFE_INTEGER,
    CanonicalizationError,
    canonicalize,
    digest,
)
from srd_rules_engine.core.combat import Weapon, attack_resolver, initiative_order
from srd_rules_engine.core.d20 import (
    DAMAGE_OFFSET,
    DIE_SIDES,
    REPLACEMENT_OFFSET,
    Adjustment,
    Advantage,
    D20Result,
    D20Test,
    Modifier,
    Override,
    Replacement,
    TestKind,
    replace_die,
)
from srd_rules_engine.core.death import (
    DEATH_SAVE_DC,
    DEATH_SAVE_VERIFICATION,
    death_save_resolver,
)
from srd_rules_engine.core.inventory import (
    ENGINE_SHAPES,
    Inventory,
    Shape,
    coverage_report,
    load_inventory,
)
from srd_rules_engine.core.ledger import Ledger, LedgerUnavailable
from srd_rules_engine.core.ledger_reader import (
    READER_VERSION,
    Entry,
    Finding,
    LedgerReport,
    read_ledger,
    repair_truncated_tail,
    summarize,
)
from srd_rules_engine.core.memory_port import (
    FACT_WRITE,
    DefaultKind,
    Fact,
    FactType,
    LedgerBackedPort,
    MemoryError_,
    MemoryPort,
    Provenance,
    Resolution,
    ValueKind,
    Writer,
    check_storable,
    fact_from_payload,
    fact_write_payload,
    is_extension,
    resolve,
)
from srd_rules_engine.core.read_surface import (
    ATTACK,
    END_TURN,
    LegalAction,
    ReadResult,
    Verdict,
    attack_key,
    attack_target,
    issue_token,
    legal_actions,
    read,
    verify,
)
from srd_rules_engine.core.report import (
    Flag,
    Replay,
    ReplayVerdict,
    SessionReport,
    Turn,
    render,
    replay,
    replay_entry,
    report_from,
    session_report,
)
from srd_rules_engine.core.rules import (
    Rule,
    RuleLoadError,
    RuleProvenance,
    Ruleset,
    Verification,
    VerificationState,
    load_fixture_ruleset,
    load_ruleset,
)
from srd_rules_engine.core.state import Combatant, EncounterState
from srd_rules_engine.core.triggers import (
    Catalogue,
    Condition,
    Grounding,
    MatchContext,
    Operator,
    Trigger,
    TriggerError,
)

__all__ = [
    "ATTACK",
    "DAMAGE_OFFSET",
    "DEATH_SAVE_DC",
    "DEATH_SAVE_VERIFICATION",
    "DIE_SIDES",
    "END_TURN",
    "ENGINE_SHAPES",
    "FACT_WRITE",
    "MAX_SAFE_INTEGER",
    "READER_VERSION",
    "REPLACEMENT_OFFSET",
    "Adjudicator",
    "Adjustment",
    "Advantage",
    "CanonicalizationError",
    "Catalogue",
    "Combatant",
    "Condition",
    "D20Result",
    "D20Test",
    "DamageDice",
    "DeathSaves",
    "Declaration",
    "DefaultKind",
    "Effect",
    "EffectKind",
    "EncounterState",
    "Entry",
    "Fact",
    "FactType",
    "Finding",
    "Flag",
    "Grounding",
    "Intent",
    "Inventory",
    "Ledger",
    "LedgerBackedPort",
    "LedgerReport",
    "LedgerUnavailable",
    "LegalAction",
    "MatchContext",
    "MemoryError_",
    "MemoryPort",
    "Modifier",
    "NarrationBounds",
    "Operator",
    "Override",
    "Proposal",
    "Provenance",
    "ReadResult",
    "RejectionCode",
    "Replacement",
    "Replay",
    "ReplayVerdict",
    "Resolution",
    "Resolver",
    "Rule",
    "RuleLoadError",
    "RuleProvenance",
    "Ruleset",
    "Ruling",
    "SessionReport",
    "Shape",
    "Status",
    "TestKind",
    "Trigger",
    "TriggerError",
    "Turn",
    "ValueKind",
    "Verdict",
    "Verification",
    "VerificationState",
    "Weapon",
    "Writer",
    "adjust_roll",
    "attack_key",
    "attack_resolver",
    "attack_target",
    "canonicalize",
    "check_storable",
    "coverage_report",
    "death_save_resolver",
    "digest",
    "fact_from_payload",
    "fact_write_payload",
    "initiative_order",
    "is_extension",
    "issue_token",
    "legal_actions",
    "load_fixture_ruleset",
    "load_inventory",
    "load_ruleset",
    "override_to_success",
    "read",
    "read_ledger",
    "render",
    "repair_truncated_tail",
    "replace_die",
    "replay",
    "replay_entry",
    "report_from",
    "resolve",
    "session_report",
    "summarize",
    "verify",
]
