"""The adjudication core — the only thing that may decide how a ruling turns out.

Holds the read surface, the legality derivation, adjudication, the trigger matcher,
the ledger, and the memory-port protocol. Two import rules bound this package, and
`tests/test_layer_boundaries.py` enforces both:

1. Nothing here may import from an outer layer. An empty `[project].dependencies`
   constrains what the package pulls in from outside, not how its own layers depend
   on each other — a core module importing an adapter would break R33 while that
   list still read empty.
2. Nothing outside the core may import a *submodule* of this package. Outer layers
   use what this module re-exports, which is what makes R34's "built over the same
   contract" a fact about the import graph rather than a description of intent.

See `docs/decisions/0011-module-layout-and-versioning.md`.
"""

from __future__ import annotations

from srd_rules_engine.core.adjudicate import (
    CONDITION_KINDS,
    Adjudicator,
    DamageDice,
    Declaration,
    Effect,
    EffectKind,
    Intent,
    NarrationBounds,
    Proposal,
    RejectionCode,
    Resolver,
    Ruling,
    Status,
    concentration_begun,
    concentration_ended,
    condition_applied,
    condition_ended,
    spell_slot_expended,
)
from srd_rules_engine.core.canonical import (
    MAX_SAFE_INTEGER,
    CanonicalizationError,
    canonicalize,
    digest,
)
from srd_rules_engine.core.casting import spell_resolver, spell_resolvers
from srd_rules_engine.core.clock import (
    HOURS_PER_DAY,
    MINUTES_PER_DAY,
    MINUTES_PER_HOUR,
    RECOVERY_OFFSET,
    STABLE_RECOVERY_HIT_POINTS,
    STABLE_RECOVERY_SIDES,
    TIME_VERIFICATION,
    Clock,
    days,
    hours,
    stable_recovery_minute,
)
from srd_rules_engine.core.combat import Weapon, attack_resolver, initiative_order

# #112: `Condition` here is the SRD condition enum — the fifteen the Rules Glossary tags
# `[Condition]`. The trigger predicate that used to hold this name is `MatchCondition`.
from srd_rules_engine.core.concentration import (
    CONCENTRATION_RULE_ID,
    CONCENTRATION_SAVE_ABILITY,
    CONCENTRATION_SAVE_VERIFICATION,
    concentration_resolver,
    concentration_rule,
)
from srd_rules_engine.core.conditions import (
    CONDITION_VERIFICATION,
    Condition,
    ConditionEffects,
    Conditions,
)
from srd_rules_engine.core.d20 import (
    DAMAGE_OFFSET,
    DIE_SIDES,
    REPLACEMENT_OFFSET,
    Adjustment,
    Advantage,
    D20Result,
    D20Test,
    Modifier,
    Override,
    Replacement,
    TestKind,
    adjust_roll,
    override_to_success,
    replace_die,
)
from srd_rules_engine.core.damage import (
    DAMAGE_VERIFICATION,
    DamageOutcome,
    DamageType,
    Defences,
    after_defences,
)
from srd_rules_engine.core.death import (
    DEATH_SAVE_DC,
    DEATH_SAVE_RULE_ID,
    DEATH_SAVE_VERIFICATION,
    death_save_resolver,
    death_save_rule,
)
from srd_rules_engine.core.duration import (
    DURATION_VERIFICATION,
    ENCOUNTER_KINDS,
    Duration,
    DurationKind,
    SaveEnds,
    SpanUnit,
    StatedSpan,
    rounds_in_minutes,
)
from srd_rules_engine.core.hazards import (
    BURNING_RULE_ID,
    BURNING_VERIFICATION,
    FALLING_VERIFICATION,
    MAX_FALLING_DICE,
    SUFFOCATION_RULE_ID,
    SUFFOCATION_VERIFICATION,
    breath_seconds,
    burning_resolver,
    burning_rule,
    falling_dice,
    falling_resolver,
    suffocation_resolver,
    suffocation_rule,
)
from srd_rules_engine.core.inventory import (
    ENGINE_SHAPES,
    Inventory,
    Shape,
    coverage_report,
    load_inventory,
)
from srd_rules_engine.core.ledger import Ledger, LedgerUnavailable
from srd_rules_engine.core.ledger_reader import (
    READER_VERSION,
    Entry,
    Finding,
    LedgerReport,
    read_ledger,
    repair_truncated_tail,
    summarize,
)
from srd_rules_engine.core.memory_port import (
    FACT_WRITE,
    DefaultKind,
    Fact,
    FactType,
    LedgerBackedPort,
    MemoryError_,
    MemoryPort,
    Provenance,
    Resolution,
    ValueKind,
    Writer,
    check_storable,
    fact_from_payload,
    fact_write_payload,
    is_extension,
    resolve,
)
from srd_rules_engine.core.perception import (
    PERCEPTION_RULE_ID,
    PERCEPTION_VERIFICATION,
    perception_resolver,
    perception_rule,
)
from srd_rules_engine.core.read_surface import (
    ATTACK,
    END_TURN,
    LegalAction,
    ReadResult,
    Verdict,
    attack_key,
    attack_target,
    cast_declared,
    cast_key,
    issue_token,
    legal_actions,
    read,
    verify,
)
from srd_rules_engine.core.report import (
    Flag,
    Replay,
    ReplayVerdict,
    SessionReport,
    Turn,
    render,
    replay,
    replay_entry,
    report_from,
    session_report,
)
from srd_rules_engine.core.rules import (
    Rule,
    RuleLoadError,
    RuleProvenance,
    Ruleset,
    Verification,
    VerificationState,
    load_fixture_ruleset,
    load_ruleset,
)
from srd_rules_engine.core.save_ends import (
    SAVE_ENDS_PREFIX,
    SAVE_ENDS_VERIFICATION,
    save_ends_resolver,
    save_ends_resolvers,
    save_ends_rule,
    save_ends_rule_id,
    save_ends_rules,
)
from srd_rules_engine.core.skills import (
    SKILL_ABILITY,
    SKILLS_VERIFICATION,
    PerceptionCheck,
    Skill,
)
from srd_rules_engine.core.state import (
    Combatant,
    ConcentrationDebt,
    DeathSaves,
    EncounterState,
    ObligationOutstanding,
)
from srd_rules_engine.core.triggers import (
    Catalogue,
    Grounding,
    MatchCondition,
    MatchContext,
    Operator,
    Trigger,
    TriggerError,
)

__all__ = [
    "ATTACK",
    "BURNING_RULE_ID",
    "BURNING_VERIFICATION",
    "CONCENTRATION_RULE_ID",
    "CONCENTRATION_SAVE_ABILITY",
    "CONCENTRATION_SAVE_VERIFICATION",
    "CONDITION_KINDS",
    "CONDITION_VERIFICATION",
    "DAMAGE_OFFSET",
    "DAMAGE_VERIFICATION",
    "DEATH_SAVE_DC",
    "DEATH_SAVE_RULE_ID",
    "DEATH_SAVE_VERIFICATION",
    "DIE_SIDES",
    "DURATION_VERIFICATION",
    "ENCOUNTER_KINDS",
    "END_TURN",
    "ENGINE_SHAPES",
    "FACT_WRITE",
    "FALLING_VERIFICATION",
    "HOURS_PER_DAY",
    "MAX_FALLING_DICE",
    "MAX_SAFE_INTEGER",
    "MINUTES_PER_DAY",
    "MINUTES_PER_HOUR",
    "PERCEPTION_RULE_ID",
    "PERCEPTION_VERIFICATION",
    "READER_VERSION",
    "RECOVERY_OFFSET",
    "REPLACEMENT_OFFSET",
    "SAVE_ENDS_PREFIX",
    "SAVE_ENDS_VERIFICATION",
    "SKILLS_VERIFICATION",
    "SKILL_ABILITY",
    "STABLE_RECOVERY_HIT_POINTS",
    "STABLE_RECOVERY_SIDES",
    "SUFFOCATION_RULE_ID",
    "SUFFOCATION_VERIFICATION",
    "TIME_VERIFICATION",
    "Adjudicator",
    "Adjustment",
    "Advantage",
    "CanonicalizationError",
    "Catalogue",
    "Clock",
    "Combatant",
    "ConcentrationDebt",
    "Condition",
    "ConditionEffects",
    "Conditions",
    "D20Result",
    "D20Test",
    "DamageDice",
    "DamageOutcome",
    "DamageType",
    "DeathSaves",
    "Declaration",
    "DefaultKind",
    "Defences",
    "Duration",
    "DurationKind",
    "Effect",
    "EffectKind",
    "EncounterState",
    "Entry",
    "Fact",
    "FactType",
    "Finding",
    "Flag",
    "Grounding",
    "Intent",
    "Inventory",
    "Ledger",
    "LedgerBackedPort",
    "LedgerReport",
    "LedgerUnavailable",
    "LegalAction",
    "MatchCondition",
    "MatchContext",
    "MemoryError_",
    "MemoryPort",
    "Modifier",
    "NarrationBounds",
    "ObligationOutstanding",
    "Operator",
    "Override",
    "PerceptionCheck",
    "Proposal",
    "Provenance",
    "ReadResult",
    "RejectionCode",
    "Replacement",
    "Replay",
    "ReplayVerdict",
    "Resolution",
    "Resolver",
    "Rule",
    "RuleLoadError",
    "RuleProvenance",
    "Ruleset",
    "Ruling",
    "SaveEnds",
    "SessionReport",
    "Shape",
    "Skill",
    "SpanUnit",
    "StatedSpan",
    "Status",
    "TestKind",
    "Trigger",
    "TriggerError",
    "Turn",
    "ValueKind",
    "Verdict",
    "Verification",
    "VerificationState",
    "Weapon",
    "Writer",
    "adjust_roll",
    "after_defences",
    "attack_key",
    "attack_resolver",
    "attack_target",
    "breath_seconds",
    "burning_resolver",
    "burning_rule",
    "canonicalize",
    "cast_declared",
    "cast_key",
    "check_storable",
    "concentration_begun",
    "concentration_ended",
    "concentration_resolver",
    "concentration_rule",
    "condition_applied",
    "condition_ended",
    "coverage_report",
    "days",
    "death_save_resolver",
    "death_save_rule",
    "digest",
    "fact_from_payload",
    "fact_write_payload",
    "falling_dice",
    "falling_resolver",
    "hours",
    "initiative_order",
    "is_extension",
    "issue_token",
    "legal_actions",
    "load_fixture_ruleset",
    "load_inventory",
    "load_ruleset",
    "override_to_success",
    "perception_resolver",
    "perception_rule",
    "read",
    "read_ledger",
    "render",
    "repair_truncated_tail",
    "replace_die",
    "replay",
    "replay_entry",
    "report_from",
    "resolve",
    "rounds_in_minutes",
    "save_ends_resolver",
    "save_ends_resolvers",
    "save_ends_rule",
    "save_ends_rule_id",
    "save_ends_rules",
    "session_report",
    "spell_resolver",
    "spell_resolvers",
    "spell_slot_expended",
    "stable_recovery_minute",
    "suffocation_resolver",
    "suffocation_rule",
    "summarize",
    "verify",
]
