#!/usr/bin/env python3
"""Render the README's decision-record index from the records themselves (#282).

    scripts/render_record_index.py            # print the list
    scripts/render_record_index.py --check    # exit non-zero if README.md disagrees

## Why generated rather than curated

[#282](https://github.com/eddiefiggie/srd-rules-engine/issues/282) offered three options —
complete the list, replace it with a pointer, or curate it and say so — and framed the choice
as honesty against length. That framing had a false premise: **the hand-written list was 64
lines for 22 records**, because each entry restated the record's title as a gloss and wrapped
over two or three lines. A generated one-line entry per record covers all 45 in 45 lines, so
completeness is *shorter* than the partial list it replaces.

It is shorter because the restatement goes. This repository's record titles are already
sentences — "An item that leaves a creature is an object, and where it lands is unstated" — so
the gloss was a paraphrase of the heading three lines below it, which is a second place for
the same claim to drift.

## What it reads

The first line of each record (`# NNNN — Title`) and the issue numbers on its `**Settles:**`
line. Both are load-bearing elsewhere: the title is the record's own claim, and the Settles
line is what `AGENTS.md` requires a gate to name.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DECISIONS = REPO_ROOT / "docs" / "decisions"
README = REPO_ROOT / "README.md"

RECORD = re.compile(r"^\d{4}-[a-z0-9-]+\.md$")
TITLE = re.compile(r"^# (\d{4}) — (.+)$")
SETTLES = re.compile(r"^- \*\*Settles:\*\*(.+?)(?=\n- \*\*|\n\n)", re.S | re.M)
ISSUE = re.compile(r"/issues/(\d+)")

START = "<!-- record-index: generated by scripts/render_record_index.py -->"
END = "<!-- /record-index -->"

ISSUE_URL = "https://github.com/eddiefiggie/srd-rules-engine/issues"


def entry(path: Path) -> str:
    """One list item for one record."""
    text = path.read_text(encoding="utf-8")
    match = TITLE.match(text.splitlines()[0])
    if match is None:
        raise ValueError(f"{path.name}: first line is not '# NNNN — Title'")
    number, title = match.groups()

    settles = SETTLES.search(text)
    issues = sorted({int(n) for n in ISSUE.findall(settles.group(1))}) if settles else []
    closes = ", ".join(f"[#{n}]({ISSUE_URL}/{n})" for n in issues)
    tail = f" — settles {closes}" if closes else ""
    return f"- [{number} — {title}](docs/decisions/{path.name}){tail}"


def render() -> str:
    """The whole index, between its markers, exactly as the README should carry it."""
    records = sorted(p for p in DECISIONS.iterdir() if RECORD.match(p.name))
    if not records:
        raise ValueError("no records matched; the glob is reading nothing")
    return "\n".join([START, *(entry(p) for p in records), END])


def readme_index(text: str) -> str | None:
    """The block the README currently carries, or `None` if the markers are missing."""
    start = text.find(START)
    end = text.find(END)
    if start == -1 or end == -1:
        return None
    return text[start : end + len(END)]


def main(argv: list[str]) -> int:
    rendered = render()
    if "--check" not in argv:
        print(rendered)
        return 0

    current = readme_index(README.read_text(encoding="utf-8"))
    if current is None:
        print(f"README.md carries no record index between {START!r} and {END!r}", file=sys.stderr)
        return 1
    if current != rendered:
        print(
            "README.md's record index is out of date. Regenerate it:\n"
            "    scripts/render_record_index.py",
            file=sys.stderr,
        )
        return 1
    listed = rendered.count("\n") - 1
    print(f"  ok  the README lists all {listed} records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
